# fly.toml app configuration file generated for radical-be-svc on 2024-05-23T11:08:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'radical-be-svc'
primary_region = 'ams'

[build]

[env]
  NYT_API_BASE_URL = 'https://api.nytimes.com/svc/books/v3'
  NYT_API_KEY = '0x4lveXQSmS7r0wGmUaw0uGOg2KAnFjM'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
